### ISSUE TITLE
Android XML Remote config file not found

### ISSUE THREAD

**Issue by junavarro** [chemerisuk/cordova-plugin-firebase-config#16]
Hello, I having an issue related to the ionic config.xml in android.

I can not set the XML remote_config_file in configt.xml in order to provide a default local configurations. If I try to set a file when I call the getString from the local resource, It brings null.

How do I set a file to my ionic project, so I can apply default config parameters and read them in my app when it does not have internet connection.

Thank you so much.
Juan

**Comment by chemerisuk** [comment]
Better to ask ionic team.
