### ISSUE TITLE
Manifest merger failed

### ISSUE THREAD

**Issue by frankcs** [chemerisuk/cordova-plugin-firebase-config#17]
Thank you for creating this plugin, i would really like to use it in an ionic app. The problem here is that i'm trying to integrate using capacitor trough ionic-native and after following the installation instructions I'm getting the error described here:

https://github.com/ionic-team/ionic-native/issues/3341

Could you please support?

**Comment by jcesarmobile** [comment]
Looks related to the plugin using Android X.
You can try to update to Capacitor 2.0.0-beta.0 as it supports Android X

**Comment by chemerisuk** [comment]
Closing, since this plugin doesn't have AndroidX dependencies.
