### ISSUE TITLE
promise not working in minifyEnabled true

### ISSUE THREAD

**Issue by jucedadev** [chemerisuk/cordova-plugin-firebase-config#18]
cordova.plugins.firebase.config.fetch(1).then(function() {alert("d");}); 
Not working 

use roles cordova plugins proguard

-keep class by.chemerisuk.cordova.firebase.** {*; }
-keep class by.chemerisuk.cordova.firebase.*

**Comment by chemerisuk** [comment]
Add all rules from the section below:

https://github.com/chemerisuk/cordova-support-android-plugin#proguard-notes
