### ISSUE TITLE
 Vulnerability in rooted cell phones

### ISSUE THREAD

**Issue by jucedadev** [chemerisuk/cordova-plugin-firebase-config#20]
Hello, in advance I thank this project very much since I have been using it for quite some time. My query is the sgt:

- After having carried out several security tests that my account that entering the data / files folder of my app finds a file saved in json format without any type of encryption with the configuration that I send from my firebase console. I was surprised that it seemed everything I sent and would like to know if there is any way to correct this without the need to send an encrypted configuration manually from the console. Thanks

Tested on a Samsung 4.4

**Comment by chemerisuk** [comment]
@Javieralonso18 I'm not SDK developer, better to ask Google Team.
