### ISSUE TITLE
IOS error FIREBASE POD VERSION is not updated

### ISSUE THREAD

**Issue by Eduardochimchek** [chemerisuk/cordova-plugin-firebase-config#25]
When I use the config together with cordova-plugin-firebase-messaging (in version 8.0.1) it gives an error in IOS_FIREBASE_POD_VERSION, because in the updated cordova-plugin-firebase-messaging it is "**10.17.0**" and in cordova-plugin-firebase-config "**9.3.0**", an error occurs when compiling on iOS.

To solve it, just update the IOS_FIREBASE_POD_VERSION to "**10.17.0**", I did it by variable and it worked

@chemerisuk

**Comment by chemerisuk** [comment]
v8 is available now with the appropriate versions.
