### ISSUE TITLE
Error incompatible cordova-android@6.4.0

### ISSUE THREAD

**Issue by Altitechlab** [chemerisuk/cordova-plugin-firebase-config#8]
I couldn't install this plugin because I'm using cordova-android@6.4.0
If I upgrade up to cordova-android@7.0.0 it made many issues. 
As you know cordova-android@7.0.0 have many issues which there many plugin doesn't support.
If possible, please downgrade this plugin to cordova-android@6.4.0?

Thank you!

**Comment by chemerisuk** [comment]
@MathiewNguyen sorry, no plans to support old cordova-android versions. You can still use earlier versions of the plugin (before version 1).
